### ISSUE TITLE
Atom decoding branch is flipped for utf8 vs. latin1 

### ISSUE THREAD

**Issue by jyc** [timotejroiko/wetf#1]
Thanks for making this library! Looks great so far, and I especially appreciate the documentation & benchmarks.

While trying to use in an environment where I had to disable the latin1 TextDecoder (because my polyfill only supports utf8), I noticed that UTF8 atoms (type 119, or [SMALL_ATOM_UTF8_EXT](https://www.erlang.org/doc/apps/erts/erl_ext_dist.html#small_atom_ext-deprecated)) were being decoded through the latin1 codepath. I think that's because this check here:

https://github.com/timotejroiko/wetf/blob/main/src/unpacker.js#L149

... sets the `utf` argument of `_resolveAtom` to `true` when `type < 118`, which I think is inverted—the tags are:

- 100 ATOM_EXT (latin1)
- 115 SMALL_ATOM_EXT (latin1)
- 118 ATOM_UTF8_EXT (utf8)
- 119 SMALL_ATOM_UTF8_EXT (utf8)

Thanks again for the great library! I'm happy to open a 1-line PR if you'd like!

**Comment by jyc** [comment]
Went ahead and made PR in case it helps!

**Comment by timotejroiko** [comment]
I cant believe this went unnoticed for so long hahaha, thanks!

**Comment by jyc** [comment]
no problem, thanks again for the library & for going above-and-beyond w/ the high quality docs & packaging!
